CREATE TABLE anime
(
    id             int PRIMARY KEY,
    title          text          NOT NULL,
    mal_score      decimal(5, 2) NOT NULL,
    genres         text          NOT NULL,
    synopsis       text          NOT NULL,
    title_english  text          NULL,
    title_japanese text          NOT NULL,
    title_synonyms text          NULL,
    image_url      text          NOT NULL,
    type           text          NOT NULL,
    source         text          NOT NULL,
    status         text          NOT NULL,
    airing         boolean       NOT NULL,
    aired_string   text          NOT NULL,
    aired          jsonb         NOT NULL,
    duration       text          NOT NULL,
    rating         text          NOT NULL,
    producer       text          NULL,
    studio         text          NULL,
    opening_theme  text[]        NOT NULL,
    ending_theme   text[]        NOT NULL,
    created_at     timestamptz   NOT NULL,
    updated_at     timestamptz   NOT NULL
);