name: Reusable build workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Install dependencies
        run: go mod tidy

      - name: Build application
        run: go build -v -o ./anitrackr-server ./cmd/app/main.go

      - name: Run tests
        run: go test -v ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-binary
          path: .