name: Deploy to Production
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: server-binary
          path: .

      - name: Copy binary to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          source: ./anitrackr-server
          target: /home/${{ secrets.SERVER_USER }}/deployments/anitrackr-server

      - name: Restart application
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            chmod +x /home/${{ secrets.SERVER_USER }}/deployments/anitrackr-server/anitrackr-server 
            sudo systemctl restart anitrackr-server.service
